### ISSUE TITLE
Very slow startup on Arch Linux

### ISSUE THREAD

**Issue by laktak** [artur-shaik/vim-javacomplete2#326] opened 2017-04-30 21:48 UTC
## Actual behavior (Required!)
vim-javacomplete2 takes forever (as in >1min) to load.

## The steps to reproduce actual behavior (Required!)

```
~/.../vim-javacomplete2/libs$ time java -cp javavi/target/classes:javavi_log4j-api.jar:javavi_log4j-core.jar:javaparser.jar kg.ash.javavi -version
2.3.7.3
real    1m0.999s
user    0m0.833s
sys     0m0.183s
```

I also tried to profile:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1  60.854183   0.000117  javacomplete#Start()
    1  60.853499   0.014835  javacomplete#server#Start()
    1  60.745097   0.000098  <SNR>69_GetServerAppVersion()
    1   0.347102   0.339290  javacomplete#server#Terminate()
    1   0.092862   0.001741  javacomplete#server#GetClassPath()
    1   0.089188   0.000119  <SNR>69_System()
    8   0.004287   0.004231  javacomplete#util#GlobPathList()
    2   0.003857   0.000057  <SNR>69_GetJavaviClassPath()
    1   0.003097   0.000309  <SNR>13_SynSet()
[..]
```

fyi I had to compile `javavi` manually with `mvn -f ~/.vim/plugged/vim-javacomplete2/libs/javavi compile`.

This may be similar to #309 

## Environment (Required!)
 * OS: Arch Linux (current)
 * Vim version: 8.0.586
 * jdk8-openjdk 8.u121-1

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.
* Even, if you wish, I can set `g:JavaComplete_JavaviDebug` to `1`, than set `g:JavaComplete_JavaviLogfileDirectory`, and put here server logs, too.

**Comment by DonnieWest** [comment] 2017-04-30 22:00
@laktak another Arch Linux user here. Have you tried using Oracle's JDK? I don't believe I'm experiencing any slowness here while using it but when I get the opportunity I'll do some profiling to make sure

**Comment by laktak** [comment] 2017-04-30 22:37
@DonnieWest how did you install the Oracle JDK? I uninstalled the openjdk and ran `sudo apacman -S jdk` 

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

But the issue still persists.

**Comment by DonnieWest** [comment] 2017-04-30 22:51
Here's some profiling I did on my machine, admittedly without a minimal config

## Environment
```
- Vim Version: NVIM v0.2.0-1461-ge4dcf756a
- OS: Archlinux (current)
```


## OpenJDK
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode
```

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   23   0.750119   0.688859  provider#python#Call()
    2   0.702410   0.000376  javacomplete#Start()
    2   0.701775   0.008160  javacomplete#server#Start()
    1   0.589696   0.587416  <SNR>158_GetServerAppVersion()
    1   0.363840   0.362830  javacomplete#server#Terminate()
    8   0.342369   0.000317  remote#host#Require()
    3   0.342052   0.342019  provider#pythonx#Require()
    1   0.332828   0.000909  <SNR>153_RemoveCurrentFromCache()
    3   0.329343   0.324922  javacomplete#server#Communicate()
    7   0.283577   0.000701  remote#define#AutocmdBootstrap()
   18   0.113473   0.000642  airline#extensions#branch#head()
    9   0.113313   0.003104  airline#extensions#hunks#get_hunks()
    9   0.110208   0.000337  <SNR>134_get_hunks()
    9   0.109871   0.000158  <SNR>134_get_hunks_gitgutter()
    9   0.108910   0.000115  <SNR>134_is_branch_empty()
   18   0.105313   0.001687  <SNR>136_update_untracked()
    2   0.103010   0.102971  airline#util#system()
    1   0.100818   0.001074  javacomplete#server#GetClassPath()
    1   0.091901   0.091873  <SNR>158_System()
    6   0.069595   0.000520  gitgutter#async#handle_diff_job_nvim()
```

## Oracle's JDK

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   23   0.750119   0.688859  provider#python#Call()
    2   0.702410   0.000376  javacomplete#Start()
    2   0.701775   0.008160  javacomplete#server#Start()
    1   0.589696   0.587416  <SNR>158_GetServerAppVersion()
    1   0.363840   0.362830  javacomplete#server#Terminate()
    8   0.342369   0.000317  remote#host#Require()
    3   0.342052   0.342019  provider#pythonx#Require()
    1   0.332828   0.000909  <SNR>153_RemoveCurrentFromCache()
    3   0.329343   0.324922  javacomplete#server#Communicate()
    7   0.283577   0.000701  remote#define#AutocmdBootstrap()
   18   0.113473   0.000642  airline#extensions#branch#head()
    9   0.113313   0.003104  airline#extensions#hunks#get_hunks()
    9   0.110208   0.000337  <SNR>134_get_hunks()
    9   0.109871   0.000158  <SNR>134_get_hunks_gitgutter()
    9   0.108910   0.000115  <SNR>134_is_branch_empty()
   18   0.105313   0.001687  <SNR>136_update_untracked()
    2   0.103010   0.102971  airline#util#system()
    1   0.100818   0.001074  javacomplete#server#GetClassPath()
    1   0.091901   0.091873  <SNR>158_System()
    6   0.069595   0.000520  gitgutter#async#handle_diff_job_nvim()
```

Sorry, it seems we can rule out the version of Java. I don't have regular VIM installed, so, it's possible that there's some sort of regression in the latest version of VIM? Would you mind trying the latest version of Neovim to see if that's the case?

**Comment by laktak** [comment] 2017-05-01 07:29
Thanks, I can try neovim when I get back. 

But wouldn't `javavi` taking a minute to display it's version information indicate some problem with the java part/outside of vim?

**Comment by artur-shaik** [comment] 2017-05-01 12:04
Still cannot reproduce such a big startup time. I'm on OpenSuse, tried with openjdk and oracle jdk. Everytime I have 1 and half of second.

**Comment by wsdjeg** [comment] 2017-05-01 12:06
I think I get same issue, I will try to find a easy way to reproduce it.

**Comment by laktak** [comment] 2017-05-01 18:27
If it helps, I've captured an strace with `strace -o xtrace -ff -tt -T java -cp javavi/target/classes:javavi_log4j-api.jar:javavi_log4j-core.jar:javaparser.j
ar kg.ash.javavi.Javavi -version`

[trace.tar.gz](https://github.com/artur-shaik/vim-javacomplete2/files/968468/trace.tar.gz)

**Comment by artur-shaik** [comment] 2017-05-02 11:15
@laktak , by your traces, there some DBUS stuff are eating most of the start up time. Any thoughts?

**Comment by laktak** [comment] 2017-05-02 11:22
After clearing `~/.m2/repository` (and `~/.gradle/caches`) the delay is gone:

```
$ time java -cp javavi/target/classes:javavi_log4j-api.jar:javavi_log4j-core.jar:javaparser.jar kg.ash.javavi.Javavi
 -version
2.3.7.3
real    0m0.533s
user    0m0.847s
sys     0m0.160s
```

No idea what was happening there of if it's worth investigating further. 

@wsdjeg could you check if this works for you as well (and keep a backup)?

**Comment by laktak** [comment] 2017-05-02 11:26
@artur-shaik see my previous comment. On my system it now works without problems from Vim. Thanks!

**Comment by artur-shaik** [comment] 2017-05-18 07:01
But why this directories block pure java call? I just can't see.

**Comment by laktak** [comment] 2017-05-18 13:29
Sorry no idea. But removing them was the only thing I did to get it working. If it comes up again and I can reproduce it I'll let you know.

**Comment by artur-shaik** [comment] 2017-05-18 13:55
Ok, let's close it for now. Reopen for demand.

**Closed** 2017-05-18 13:55 UTC
