### ISSUE TITLE
Cannot build gradle classpath

### ISSUE THREAD

**Issue by brcolow** [artur-shaik/vim-javacomplete2#219] opened 2016-03-11 08:03 UTC
Using neovim version `NVIM v0.1.3-244-g3e0fab6`, Arch Linux, gnome-terminal, I am getting the following errors when opening this Java project: https://github.com/TestFX/TestFX.

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/dev/testfx/subprojects/testfx-core/src/main/java/org/testfx/matcher/control/TableViewMatchers.java" 97L, 3920C
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
FAILURE: Build failed with an exception.
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
* What went wrong:
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
Failed to notify build listener.
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
> java.lang.NullPointerException (no error message)
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
> java.lang.NullPointerException (no error message)
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
> java.lang.NullPointerException (no error message)
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
* Try:
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Failed to build gradle classpath
```

**Comment by siphiuel** [comment] 2016-03-11 15:20
Can confirm in my case as well (Neovim 0.1.2, OS X 10.11), with the following messages:

```
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
FAILURE: Build failed with an exception.
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
* Where:
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
Script '/Users/vvlasov/.vim/bundle/vim-javacomplete2/classpath.gradle' line: 24
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
* What went wrong:
Error detected while processing function javacomplete#classpath#gradle#BuildClasspathHandler:
line   33:
Execution failed for task ':classpath'.
```
Plugin works perfectly for Vim (7.4.1525).

**Comment by artur-shaik** [comment] 2016-03-12 15:39
Hm, cannot reproduce with `0.1.3-340`. Can you get what exactly happened with gradle execution?

**Comment by brcolow** [comment] 2016-03-12 19:23
Sure, how does one do that?

**Comment by wsdjeg** [comment] 2016-03-13 11:38
I can not reprodue this issue.
`echo g:JavaComplete_Libpath`
show me 
```
./home/wsdjeg/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/18.0/cce0823396aa693798f8882e64213b1772032b09/guava-18.0.jar:/home/wsdjeg/.grad
le/caches/modules-2/files-2.1/org.controlsfx/openjfx-dialogs/1.0.2/c53eb044b9cc2a22365da7272ec8f32960b1b6df/openjfx-dialogs-1.0.2.jar:/home/wsdjeg/fork
s/TestFX/subprojects/testfx-junit/src/main/java:/home/wsdjeg/forks/TestFX/subprojects/testfx-core/src/main/java:/home/wsdjeg/forks/TestFX/subprojects/t
estfx-legacy/src/main/java:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/org.controlsfx/controlsfx/8.20.8/62647327dc0c0853596738caea794f132912f747/co
ntrolsfx-8.20.8.jar:/home/wsdjeg/forks/TestFX/subprojects/testfx-legacy/src/test/java:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/
2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/home/wsdjeg/forks/TestFX/subprojects/testfx-core/build/libs/testfx-core-4.0.2-alpha.jar:/home/
wsdjeg/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-all/1.3/63a21ebc981131004ad02e0434e799fd7f3a8d5a/hamcrest-all-1.3.jar:/home/wsdjeg/fork
s/TestFX/subprojects/testfx-core/src/test/java:/home/wsdjeg/forks/TestFX/subprojects/testfx-junit/src/test/java:/home/wsdjeg/.gradle/caches/modules-2/f
iles-2.1/org.mockito/mockito-all/1.9.5/79a8984096fc6591c1e3690e07d41be506356fa5/mockito-all-1.9.5.jar:/home/wsdjeg/.gradle/caches/modules-2/files-2.1/o
rg.testfx/openjfx-monocle/1.8.0_20/9859038affe2fd08c40c43ca19790687a5d56107/openjfx-monocle-1.8.0_20.jar                                               
Press ENTER or type command to continue                                                                  
```

**Comment by artur-shaik** [comment] 2016-03-13 16:13
@brcolow you can try enable `g:JavaComplete_ShowExternalCommandsOutput` to see output.

**Comment by brcolow** [comment] 2016-03-13 22:48
It seems that this is not an issue with Javacomplete2 itself, but with gradle. Because, if I run:

`gradle classpath build process --debug --stacktrace` in root project directory of TestFX project, I get an error. So, it is not Javacomplete2's problem I think. For reference here is the (very long) [stack trace](http://pastebin.com/DzmWcsfi).

**Comment by wsdjeg** [comment] 2016-03-13 23:43
sorry.as Shougo says.most people use gradle as default.so we change to gradle

**Comment by DonnieWest** [comment] 2016-03-14 02:38
If a gradle wrapper has been included in a project, the expectation is that the wrapper will be used instead of the system binary.

**Comment by wsdjeg** [comment] 2016-03-14 03:21
so you means ./gradlew should be default if it is exist?

from my phone

-------- 原始邮件 --------
主题：Re: [vim-javacomplete2] Cannot build gradle classpath (#219)
发件人：Donnie West
收件人：artur-shaik/vim-javacomplete2
抄送：Wang Shidong

If a gradle wrapper has been included in a project, the expectation is that the wrapper will be used instead of the system binary.

---

**Comment by DonnieWest** [comment] 2016-03-14 03:40
Correct, if a user has a ./gradlew in their project then that is intentional. It's done that way so that the same version of Gradle can be used regardless of what is installed on a machine (For CI or keep your software team on the same version of Gradle)

**Comment by artur-shaik** [comment] 2016-03-14 05:43
So, should we give priority to local executable `./gradlew`?

**Comment by wsdjeg** [comment] 2016-03-14 05:54
we make the change because @Shougo ask me this question in gitter.im,so if we change the default value,I think maybe he should know about it.

**Comment by Shougo** [comment] 2016-03-14 12:22
If this change works in Android project properly, :+1:

**Comment by wsdjeg** [comment] 2016-03-14 12:26
thanks for reply,I will try to add this feature after #222 be merged.

**Comment by wsdjeg** [comment] 2016-03-14 13:38
@artur-shaik I need to use the absolute path of `./gradlew` because maybe some people do not use vim-rooter. I think maybe that is why @Shougo get freeze when open an java file.

**Comment by artur-shaik** [comment] 2016-03-14 13:46
May be in this case you can use `g:JavaComplete_GradlePath`?

On 03-14 (06:38), Wang Shidong wrote:
>    [1]@artur-shaik I need to use the absolute path of ./gradlew because maybe
>    some people do not use vim-rooter. I think maybe that is why [2]@Shougo
>    get freeze when open an java file.
> 
>    —
>    Reply to this email directly or [3]view it on GitHub.
> 
>    Reverse link: [4]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik
>    2. https://github.com/Shougo
>    3. https://github.com/artur-shaik/vim-javacomplete2/issues/219#issuecomment-196313731
>    4. https://github.com/artur-shaik/vim-javacomplete2/issues/219#issuecomment-196313731

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment] 2016-03-14 14:27
Done

**Closed** 2016-03-14 15:43 UTC

**Comment by wsdjeg** [comment] 2016-04-12 13:23
@brcolow in gitter.im,you want me testting https://github.com/elastic/elasticsearch.git , but it is too lager to clone.after read the PRs, I found a GOOD reason for `do not use gradle wapper`.https://github.com/elastic/elasticsearch/pull/13744.
and I do not know whether javacomplete2 works well with maven submodule project or gradle submodule project.if JC2 only put all submodule project's classpath together,it will be very slow.
