### ISSUE TITLE
does not work on wsl Ubuntu20.04

### ISSUE THREAD

**Issue by slowens-dev** [artur-shaik/vim-javacomplete2#446] opened 2020-11-16 03:02 UTC
## Actual behavior (Required!)
does nothing

## Expected behavior (Required!)
does what it says it does, autocompletes java

## The steps to reproduce actual behavior (Required!)
 1. follow steps detailed in installation sections exactly
 2. attempt to use the plugin
 3. nothing happend

## Environment (Required!)
 * OS: wsl Ubuntu 20.04
 * Vim version: 8.1.2269
 * Neovim version: 0.4.3

## Q&A
* Yes, I tried minimal .vimrc configuraion.
* Yes, I have enabled logs with `JCdebugEnableLogs` and can put here content of `JCdebugGetLogContent` command, if you need.

1 empty line

* Even, if you wish, I can set `g:JavaComplete_JavaviLogLevel` to `'debug'`, then set `g:JavaComplete_JavaviLogDirectory`, and put here server logs, too.

**Comment by artur-shaik** [comment] 2020-11-16 04:01
Hi, what if you press `<C-x><C-o>` after the dot?

**Comment by artur-shaik** [comment] 2020-11-18 04:08
Duplicate of #431

**Closed by artur-shaik** 2020-11-18 04:08 UTC

**Comment by arijitmazumdar** [comment] 2021-01-27 01:50
It worked with me with <C-x><C-o>. I can see all the methods of a class to be selected. What are these options ? Is there any docs where I can read about them?

**Comment by artur-shaik** [comment] 2021-01-27 02:13
@arijitmazumdar can you illustrate your question?

**Comment by arijitmazumdar** [comment] 2021-01-31 05:56
> @arijitmazumdar can you illustrate your question?

![Screenshot from 2021-01-31 11-23-39](https://user-images.githubusercontent.com/13167516/106375995-080a7480-63b7-11eb-892c-cf01227d85cf.png)
 Please see the attached image after I added autocomplete. There are 2 tabs [Scratch][Preview] on the top. How to get rid of them?

**Comment by artur-shaik** [comment] 2021-02-03 14:03
Seems like it is not javacomplete function. What are you using for triggering completion? YouCompleteMe or deoplete may be?
